package com.partywave.backend.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AppUserStatsAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppUserStatsAllPropertiesEquals(AppUserStats expected, AppUserStats actual) {
        assertAppUserStatsAutoGeneratedPropertiesEquals(expected, actual);
        assertAppUserStatsAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppUserStatsAllUpdatablePropertiesEquals(AppUserStats expected, AppUserStats actual) {
        assertAppUserStatsUpdatableFieldsEquals(expected, actual);
        assertAppUserStatsUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppUserStatsAutoGeneratedPropertiesEquals(AppUserStats expected, AppUserStats actual) {
        assertThat(actual)
            .as("Verify AppUserStats auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppUserStatsUpdatableFieldsEquals(AppUserStats expected, AppUserStats actual) {
        assertThat(actual)
            .as("Verify AppUserStats relevant properties")
            .satisfies(a -> assertThat(a.getTotalLike()).as("check totalLike").isEqualTo(expected.getTotalLike()))
            .satisfies(a -> assertThat(a.getTotalDislike()).as("check totalDislike").isEqualTo(expected.getTotalDislike()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppUserStatsUpdatableRelationshipsEquals(AppUserStats expected, AppUserStats actual) {
        // empty method
    }
}
