package com.partywave.backend.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AppUserImageAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppUserImageAllPropertiesEquals(AppUserImage expected, AppUserImage actual) {
        assertAppUserImageAutoGeneratedPropertiesEquals(expected, actual);
        assertAppUserImageAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppUserImageAllUpdatablePropertiesEquals(AppUserImage expected, AppUserImage actual) {
        assertAppUserImageUpdatableFieldsEquals(expected, actual);
        assertAppUserImageUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppUserImageAutoGeneratedPropertiesEquals(AppUserImage expected, AppUserImage actual) {
        assertThat(actual)
            .as("Verify AppUserImage auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppUserImageUpdatableFieldsEquals(AppUserImage expected, AppUserImage actual) {
        assertThat(actual)
            .as("Verify AppUserImage relevant properties")
            .satisfies(a -> assertThat(a.getUrl()).as("check url").isEqualTo(expected.getUrl()))
            .satisfies(a -> assertThat(a.getHeight()).as("check height").isEqualTo(expected.getHeight()))
            .satisfies(a -> assertThat(a.getWidth()).as("check width").isEqualTo(expected.getWidth()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppUserImageUpdatableRelationshipsEquals(AppUserImage expected, AppUserImage actual) {
        assertThat(actual)
            .as("Verify AppUserImage relationships")
            .satisfies(a -> assertThat(a.getAppUser()).as("check appUser").isEqualTo(expected.getAppUser()));
    }
}
