package com.partywave.backend.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ChatMessageAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChatMessageAllPropertiesEquals(ChatMessage expected, ChatMessage actual) {
        assertChatMessageAutoGeneratedPropertiesEquals(expected, actual);
        assertChatMessageAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChatMessageAllUpdatablePropertiesEquals(ChatMessage expected, ChatMessage actual) {
        assertChatMessageUpdatableFieldsEquals(expected, actual);
        assertChatMessageUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChatMessageAutoGeneratedPropertiesEquals(ChatMessage expected, ChatMessage actual) {
        assertThat(actual)
            .as("Verify ChatMessage auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChatMessageUpdatableFieldsEquals(ChatMessage expected, ChatMessage actual) {
        assertThat(actual)
            .as("Verify ChatMessage relevant properties")
            .satisfies(a -> assertThat(a.getContent()).as("check content").isEqualTo(expected.getContent()))
            .satisfies(a -> assertThat(a.getSentAt()).as("check sentAt").isEqualTo(expected.getSentAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChatMessageUpdatableRelationshipsEquals(ChatMessage expected, ChatMessage actual) {
        assertThat(actual)
            .as("Verify ChatMessage relationships")
            .satisfies(a -> assertThat(a.getRoom()).as("check room").isEqualTo(expected.getRoom()))
            .satisfies(a -> assertThat(a.getSender()).as("check sender").isEqualTo(expected.getSender()));
    }
}
