package com.partywave.backend.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RefreshTokenAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRefreshTokenAllPropertiesEquals(RefreshToken expected, RefreshToken actual) {
        assertRefreshTokenAutoGeneratedPropertiesEquals(expected, actual);
        assertRefreshTokenAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRefreshTokenAllUpdatablePropertiesEquals(RefreshToken expected, RefreshToken actual) {
        assertRefreshTokenUpdatableFieldsEquals(expected, actual);
        assertRefreshTokenUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRefreshTokenAutoGeneratedPropertiesEquals(RefreshToken expected, RefreshToken actual) {
        assertThat(actual)
            .as("Verify RefreshToken auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRefreshTokenUpdatableFieldsEquals(RefreshToken expected, RefreshToken actual) {
        assertThat(actual)
            .as("Verify RefreshToken relevant properties")
            .satisfies(a -> assertThat(a.getTokenHash()).as("check tokenHash").isEqualTo(expected.getTokenHash()))
            .satisfies(a -> assertThat(a.getExpiresAt()).as("check expiresAt").isEqualTo(expected.getExpiresAt()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getRevokedAt()).as("check revokedAt").isEqualTo(expected.getRevokedAt()))
            .satisfies(a -> assertThat(a.getDeviceInfo()).as("check deviceInfo").isEqualTo(expected.getDeviceInfo()))
            .satisfies(a -> assertThat(a.getIpAddress()).as("check ipAddress").isEqualTo(expected.getIpAddress()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRefreshTokenUpdatableRelationshipsEquals(RefreshToken expected, RefreshToken actual) {
        assertThat(actual)
            .as("Verify RefreshToken relationships")
            .satisfies(a -> assertThat(a.getAppUser()).as("check appUser").isEqualTo(expected.getAppUser()));
    }
}
