package com.partywave.backend.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RoomAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRoomAllPropertiesEquals(Room expected, Room actual) {
        assertRoomAutoGeneratedPropertiesEquals(expected, actual);
        assertRoomAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRoomAllUpdatablePropertiesEquals(Room expected, Room actual) {
        assertRoomUpdatableFieldsEquals(expected, actual);
        assertRoomUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRoomAutoGeneratedPropertiesEquals(Room expected, Room actual) {
        assertThat(actual)
            .as("Verify Room auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRoomUpdatableFieldsEquals(Room expected, Room actual) {
        assertThat(actual)
            .as("Verify Room relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getMaxParticipants()).as("check maxParticipants").isEqualTo(expected.getMaxParticipants()))
            .satisfies(a -> assertThat(a.getIsPublic()).as("check isPublic").isEqualTo(expected.getIsPublic()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRoomUpdatableRelationshipsEquals(Room expected, Room actual) {
        assertThat(actual)
            .as("Verify Room relationships")
            .satisfies(a -> assertThat(a.getTags()).as("check tags").isEqualTo(expected.getTags()));
    }
}
