package com.partywave.backend.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RoomMemberAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRoomMemberAllPropertiesEquals(RoomMember expected, RoomMember actual) {
        assertRoomMemberAutoGeneratedPropertiesEquals(expected, actual);
        assertRoomMemberAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRoomMemberAllUpdatablePropertiesEquals(RoomMember expected, RoomMember actual) {
        assertRoomMemberUpdatableFieldsEquals(expected, actual);
        assertRoomMemberUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRoomMemberAutoGeneratedPropertiesEquals(RoomMember expected, RoomMember actual) {
        assertThat(actual)
            .as("Verify RoomMember auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRoomMemberUpdatableFieldsEquals(RoomMember expected, RoomMember actual) {
        assertThat(actual)
            .as("Verify RoomMember relevant properties")
            .satisfies(a -> assertThat(a.getJoinedAt()).as("check joinedAt").isEqualTo(expected.getJoinedAt()))
            .satisfies(a -> assertThat(a.getLastActiveAt()).as("check lastActiveAt").isEqualTo(expected.getLastActiveAt()))
            .satisfies(a -> assertThat(a.getRole()).as("check role").isEqualTo(expected.getRole()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRoomMemberUpdatableRelationshipsEquals(RoomMember expected, RoomMember actual) {
        assertThat(actual)
            .as("Verify RoomMember relationships")
            .satisfies(a -> assertThat(a.getRoom()).as("check room").isEqualTo(expected.getRoom()))
            .satisfies(a -> assertThat(a.getAppUser()).as("check appUser").isEqualTo(expected.getAppUser()));
    }
}
