package com.partywave.backend.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RoomInvitationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRoomInvitationAllPropertiesEquals(RoomInvitation expected, RoomInvitation actual) {
        assertRoomInvitationAutoGeneratedPropertiesEquals(expected, actual);
        assertRoomInvitationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRoomInvitationAllUpdatablePropertiesEquals(RoomInvitation expected, RoomInvitation actual) {
        assertRoomInvitationUpdatableFieldsEquals(expected, actual);
        assertRoomInvitationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRoomInvitationAutoGeneratedPropertiesEquals(RoomInvitation expected, RoomInvitation actual) {
        assertThat(actual)
            .as("Verify RoomInvitation auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRoomInvitationUpdatableFieldsEquals(RoomInvitation expected, RoomInvitation actual) {
        assertThat(actual)
            .as("Verify RoomInvitation relevant properties")
            .satisfies(a -> assertThat(a.getToken()).as("check token").isEqualTo(expected.getToken()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getExpiresAt()).as("check expiresAt").isEqualTo(expected.getExpiresAt()))
            .satisfies(a -> assertThat(a.getMaxUses()).as("check maxUses").isEqualTo(expected.getMaxUses()))
            .satisfies(a -> assertThat(a.getUsedCount()).as("check usedCount").isEqualTo(expected.getUsedCount()))
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRoomInvitationUpdatableRelationshipsEquals(RoomInvitation expected, RoomInvitation actual) {
        assertThat(actual)
            .as("Verify RoomInvitation relationships")
            .satisfies(a -> assertThat(a.getRoom()).as("check room").isEqualTo(expected.getRoom()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()));
    }
}
