package com.partywave.backend.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RoomAccessAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRoomAccessAllPropertiesEquals(RoomAccess expected, RoomAccess actual) {
        assertRoomAccessAutoGeneratedPropertiesEquals(expected, actual);
        assertRoomAccessAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRoomAccessAllUpdatablePropertiesEquals(RoomAccess expected, RoomAccess actual) {
        assertRoomAccessUpdatableFieldsEquals(expected, actual);
        assertRoomAccessUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRoomAccessAutoGeneratedPropertiesEquals(RoomAccess expected, RoomAccess actual) {
        assertThat(actual)
            .as("Verify RoomAccess auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRoomAccessUpdatableFieldsEquals(RoomAccess expected, RoomAccess actual) {
        assertThat(actual)
            .as("Verify RoomAccess relevant properties")
            .satisfies(a -> assertThat(a.getGrantedAt()).as("check grantedAt").isEqualTo(expected.getGrantedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRoomAccessUpdatableRelationshipsEquals(RoomAccess expected, RoomAccess actual) {
        assertThat(actual)
            .as("Verify RoomAccess relationships")
            .satisfies(a -> assertThat(a.getRoom()).as("check room").isEqualTo(expected.getRoom()))
            .satisfies(a -> assertThat(a.getAppUser()).as("check appUser").isEqualTo(expected.getAppUser()))
            .satisfies(a -> assertThat(a.getGrantedBy()).as("check grantedBy").isEqualTo(expected.getGrantedBy()));
    }
}
