package com.partywave.backend.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class UserTokenAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserTokenAllPropertiesEquals(UserToken expected, UserToken actual) {
        assertUserTokenAutoGeneratedPropertiesEquals(expected, actual);
        assertUserTokenAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserTokenAllUpdatablePropertiesEquals(UserToken expected, UserToken actual) {
        assertUserTokenUpdatableFieldsEquals(expected, actual);
        assertUserTokenUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserTokenAutoGeneratedPropertiesEquals(UserToken expected, UserToken actual) {
        assertThat(actual)
            .as("Verify UserToken auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserTokenUpdatableFieldsEquals(UserToken expected, UserToken actual) {
        assertThat(actual)
            .as("Verify UserToken relevant properties")
            .satisfies(a -> assertThat(a.getAccessToken()).as("check accessToken").isEqualTo(expected.getAccessToken()))
            .satisfies(a -> assertThat(a.getRefreshToken()).as("check refreshToken").isEqualTo(expected.getRefreshToken()))
            .satisfies(a -> assertThat(a.getTokenType()).as("check tokenType").isEqualTo(expected.getTokenType()))
            .satisfies(a -> assertThat(a.getExpiresAt()).as("check expiresAt").isEqualTo(expected.getExpiresAt()))
            .satisfies(a -> assertThat(a.getScope()).as("check scope").isEqualTo(expected.getScope()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserTokenUpdatableRelationshipsEquals(UserToken expected, UserToken actual) {
        assertThat(actual)
            .as("Verify UserToken relationships")
            .satisfies(a -> assertThat(a.getAppUser()).as("check appUser").isEqualTo(expected.getAppUser()));
    }
}
