package com.partywave.backend.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class VoteAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVoteAllPropertiesEquals(Vote expected, Vote actual) {
        assertVoteAutoGeneratedPropertiesEquals(expected, actual);
        assertVoteAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVoteAllUpdatablePropertiesEquals(Vote expected, Vote actual) {
        assertVoteUpdatableFieldsEquals(expected, actual);
        assertVoteUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVoteAutoGeneratedPropertiesEquals(Vote expected, Vote actual) {
        assertThat(actual)
            .as("Verify Vote auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVoteUpdatableFieldsEquals(Vote expected, Vote actual) {
        assertThat(actual)
            .as("Verify Vote relevant properties")
            .satisfies(a -> assertThat(a.getVoteType()).as("check voteType").isEqualTo(expected.getVoteType()))
            .satisfies(a -> assertThat(a.getPlaylistItemId()).as("check playlistItemId").isEqualTo(expected.getPlaylistItemId()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVoteUpdatableRelationshipsEquals(Vote expected, Vote actual) {
        assertThat(actual)
            .as("Verify Vote relationships")
            .satisfies(a -> assertThat(a.getRoom()).as("check room").isEqualTo(expected.getRoom()))
            .satisfies(a -> assertThat(a.getVoter()).as("check voter").isEqualTo(expected.getVoter()))
            .satisfies(a -> assertThat(a.getTargetUser()).as("check targetUser").isEqualTo(expected.getTargetUser()));
    }
}
